SELECT USER_ID, PRODUCT_ID
FROM ONLINE_SALE

GROUP BY USER_ID, PRODUCT_ID
HAVING COUNT(*) >=2

ORDER BY USER_ID ASC, PRODUCT_ID DESC

# 동일한 회원이 동일한 상품을 재구매한 데이터
# GROUP BY 동일한 회원, 동일한 상품
# COUNT (*) >= 2